[greeter]
background=/usr/share/backgrounds/furry-wallpaper.png
theme-name=Adwaita
icon-theme-name=gnome
font-name=Ubuntu 11
xft-antialias=true
xft-dpi=96
screensaver-timeout=60
# 隐藏用户列表，改为手动输入
show-other-users-gtk=true
# 启用键盘辅助
a11y-states=+keyboard
