#!/bin/bash
set -e
lb config \
    --bootstrap ubuntu \
    --distribution jammy \
    --architectures amd64 \
    --mirror-bootstrap https://mirrors.ustc.edu.cn/ubuntu/ \
    --mirror-chroot https://mirrors.ustc.edu.cn/ubuntu/ \
    --installer calamares \
    --tasks ubuntu-desktop-minimal \
    --image-name furry-os \
    --iso-application "Furry OS" \
    --package-lists "base desktop" \
    --hook-dir config/hooks \
    --includes config/includes.chroot \
    --iso-hybrid true \
    --uefi-image true \
    --iso-filename furry-os-amd64.iso \
    --debootstrap-options "--components=main,universe,multiverse"
